<a href="https://colab.research.google.com/github/denverkim/ppfk/blob/main/%EC%A7%80%EC%97%AD%EB%B3%84_%EC%9D%B8%EA%B5%AC%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%B6%84%EC%84%9D_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

# 1. 엑셀 파일 불러오기
file_path = "/content/지역별 인구 및 인구밀도_20250828232703.xlsx"
df = pd.read_excel(file_path, sheet_name='지역별 인구 및 인구밀도(e-나라지표)', skiprows=28)
df

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,Unnamed: 0,2020,Unnamed: 2,2021,Unnamed: 4,2022,Unnamed: 6,2023,Unnamed: 8,2024,Unnamed: 10
0,NaN,인구,인구밀도,인구,인구밀도,인구,인구밀도,인구,인구밀도,인구,인구밀도
1,계,"51,836",516,"51,770",515,"51,673",514,"51,713",515,"51,751",515
2,서울,"9,618","15,891","9,508","15,709","9,421","15,567","9,400","15,533","9,394","15,521"
3,부산,"3,356","4,358","3,334","4,328","3,303","4,282","3,284","4,258","3,265","4,232"
4,대구,"2,414","2,733","2,396","2,711","2,372","2,679","2,360","2,666","2,354","2,659"
5,인천,"2,951","2,770","2,950","2,766","2,975","2,788","3,009","2,820","3,049","2,851"
6,광주,"1,480","2,952","1,476","2,945","1,470","2,933","1,463","2,921","1,456","2,905"
7,대전,"1,492","2,764","1,482","2,747","1,472","2,728","1,474","2,731","1,473","2,729"
8,울산,"1,139","1,072","1,125","1,059","1,114","1,048","1,106","1,041","1,103","1,038"
9,세종,348,749,361,777,380,818,387,833,389,837
10,경기,"13,452","1,319","13,611","1,335","13,690","1,342","13,781","1,351","13,861","1,359"
11,강원,"1,519",90,"1,520",90,"1,527",91,"1,525",91,"1,518",90
12,충북,"1,631",220,"1,626",220,"1,623",219,"1,627",220,"1,630",220
13,충남,"2,177",264,"2,175",264,"2,186",265,"2,204",267,"2,224",270
14,전북,"1,806",224,"1,792",222,"1,777",220,"1,768",219,"1,759",218
15,전남,"1,793",145,"1,785",144,"1,775",144,"1,768",143,"1,757",142
16,경북,"2,652",139,"2,641",139,"2,626",138,"2,611",137,"2,597",136
17,경남,"3,340",317,"3,315",314,"3,287",312,"3,267",310,"3,249",308
18,제주,669,361,672,363,675,365,677,366,675,365
19,수도권,"26,021","2,193","26,069","2,196","26,086","2,197","26,190","2,206","26,304","2,215"
20,출처:,"통계청「장래인구추계 시도편 : 2022-2052」, 국토교통부「지적통계」",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,주석:,"* 수도권 : 서울, 인천, 경기",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,* 통계청『장래인구추계 시도편 : 2022-2052』의 시도별 인구와 국토교통부『지...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,* 시도별 장래인구추계는 2024년에 작성된 자료임,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,※의미분석,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,지표설명,■ 지역별 인구 및 인구밀도의 개념\n\n ° 지역별 인구란 각 지역별로 거주하는...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,지표해석,■ 지역별 인구 및 인구밀도 추세\n\n ° 인구\n - 2022년 총인구...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,유의사항,장래인구추계 시도편은 2022년 인구총조사 결과를 기초로 2024년에 작성하여 발표...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,※관련용어,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,지역면적:,지적통계자료의 지역별 면적,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,인구밀도(명/㎢):,특정 지역의 단위면적당 인구의 크기를 나타내는 지표로 지역별 인구(시도별 추계인구)...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,※지표정보,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,담당 부서 및 연락처,"통계청, 인구추계팀, 042-481-2354",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,최근 갱신일,2025-05-07(입력예정일 : 2026-04-30),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,자료 출처,"통계청『장래인구추계 시도편 : 2022-2052』, 국토교통부 『지적통계』",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,공표 주기,"『장래인구추계 시도편 : 2022-2052』2~3년, 『지적통계』매년",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# 2. 컬럼 정리
df = df.rename(columns={"Unnamed: 0": "지역"})
# 불필요한 NaN 제거
df = df.dropna(subset=["지역"])
df

,지역,2020,Unnamed: 2,2021,Unnamed: 4,2022,Unnamed: 6,2023,Unnamed: 8,2024,Unnamed: 10
1,계,"51,836",516,"51,770",515,"51,673",514,"51,713",515,"51,751",515
2,서울,"9,618","15,891","9,508","15,709","9,421","15,567","9,400","15,533","9,394","15,521"
3,부산,"3,356","4,358","3,334","4,328","3,303","4,282","3,284","4,258","3,265","4,232"
4,대구,"2,414","2,733","2,396","2,711","2,372","2,679","2,360","2,666","2,354","2,659"
5,인천,"2,951","2,770","2,950","2,766","2,975","2,788","3,009","2,820","3,049","2,851"
6,광주,"1,480","2,952","1,476","2,945","1,470","2,933","1,463","2,921","1,456","2,905"
7,대전,"1,492","2,764","1,482","2,747","1,472","2,728","1,474","2,731","1,473","2,729"
8,울산,"1,139","1,072","1,125","1,059","1,114","1,048","1,106","1,041","1,103","1,038"
9,세종,348,749,361,777,380,818,387,833,389,837
10,경기,"13,452","1,319","13,611","1,335","13,690","1,342","13,781","1,351","13,861","1,359"
11,강원,"1,519",90,"1,520",90,"1,527",91,"1,525",91,"1,518",90
12,충북,"1,631",220,"1,626",220,"1,623",219,"1,627",220,"1,630",220
13,충남,"2,177",264,"2,175",264,"2,186",265,"2,204",267,"2,224",270
14,전북,"1,806",224,"1,792",222,"1,777",220,"1,768",219,"1,759",218
15,전남,"1,793",145,"1,785",144,"1,775",144,"1,768",143,"1,757",142
16,경북,"2,652",139,"2,641",139,"2,626",138,"2,611",137,"2,597",136
17,경남,"3,340",317,"3,315",314,"3,287",312,"3,267",310,"3,249",308
18,제주,669,361,672,363,675,365,677,366,675,365
19,수도권,"26,021","2,193","26,069","2,196","26,086","2,197","26,190","2,206","26,304","2,215"
20,출처:,"통계청「장래인구추계 시도편 : 2022-2052」, 국토교통부「지적통계」",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,주석:,"* 수도권 : 서울, 인천, 경기",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,※의미분석,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,지표설명,■ 지역별 인구 및 인구밀도의 개념\n\n ° 지역별 인구란 각 지역별로 거주하는...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,지표해석,■ 지역별 인구 및 인구밀도 추세\n\n ° 인구\n - 2022년 총인구...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,유의사항,장래인구추계 시도편은 2022년 인구총조사 결과를 기초로 2024년에 작성하여 발표...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,※관련용어,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,지역면적:,지적통계자료의 지역별 면적,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,인구밀도(명/㎢):,특정 지역의 단위면적당 인구의 크기를 나타내는 지표로 지역별 인구(시도별 추계인구)...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,※지표정보,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,담당 부서 및 연락처,"통계청, 인구추계팀, 042-481-2354",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,최근 갱신일,2025-05-07(입력예정일 : 2026-04-30),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,자료 출처,"통계청『장래인구추계 시도편 : 2022-2052』, 국토교통부 『지적통계』",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,공표 주기,"『장래인구추계 시도편 : 2022-2052』2~3년, 『지적통계』매년",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
# 3. 불필요한 행 제거 (출처, 단위, 주석 제거)
df = df.loc[:19, :].copy()
df

,지역,2020,Unnamed: 2,2021,Unnamed: 4,2022,Unnamed: 6,2023,Unnamed: 8,2024,Unnamed: 10
1,계,51836.0,516.0,51770.0,515.0,51673.0,514.0,51713.0,515.0,51751.0,515.0
2,서울,9618.0,15891.0,9508.0,15709.0,9421.0,15567.0,9400.0,15533.0,9394.0,15521.0
3,부산,3356.0,4358.0,3334.0,4328.0,3303.0,4282.0,3284.0,4258.0,3265.0,4232.0
4,대구,2414.0,2733.0,2396.0,2711.0,2372.0,2679.0,2360.0,2666.0,2354.0,2659.0
5,인천,2951.0,2770.0,2950.0,2766.0,2975.0,2788.0,3009.0,2820.0,3049.0,2851.0
6,광주,1480.0,2952.0,1476.0,2945.0,1470.0,2933.0,1463.0,2921.0,1456.0,2905.0
7,대전,1492.0,2764.0,1482.0,2747.0,1472.0,2728.0,1474.0,2731.0,1473.0,2729.0
8,울산,1139.0,1072.0,1125.0,1059.0,1114.0,1048.0,1106.0,1041.0,1103.0,1038.0
9,세종,348.0,749.0,361.0,777.0,380.0,818.0,387.0,833.0,389.0,837.0
10,경기,13452.0,1319.0,13611.0,1335.0,13690.0,1342.0,13781.0,1351.0,13861.0,1359.0
11,강원,1519.0,90.0,1520.0,90.0,1527.0,91.0,1525.0,91.0,1518.0,90.0
12,충북,1631.0,220.0,1626.0,220.0,1623.0,219.0,1627.0,220.0,1630.0,220.0
13,충남,2177.0,264.0,2175.0,264.0,2186.0,265.0,2204.0,267.0,2224.0,270.0
14,전북,1806.0,224.0,1792.0,222.0,1777.0,220.0,1768.0,219.0,1759.0,218.0
15,전남,1793.0,145.0,1785.0,144.0,1775.0,144.0,1768.0,143.0,1757.0,142.0
16,경북,2652.0,139.0,2641.0,139.0,2626.0,138.0,2611.0,137.0,2597.0,136.0
17,경남,3340.0,317.0,3315.0,314.0,3287.0,312.0,3267.0,310.0,3249.0,308.0
18,제주,669.0,361.0,672.0,363.0,675.0,365.0,677.0,366.0,675.0,365.0
19,수도권,26021.0,2193.0,26069.0,2196.0,26086.0,2197.0,26190.0,2206.0,26304.0,2215.0

In [11]:
# 3. 숫자형 변환 (천 단위 구분 기호 제거)
for col in df.columns[1:]:
    df[col] = df[col].astype(str).str.replace(",", "").astype(float)
df

,지역,2020,Unnamed: 2,2021,Unnamed: 4,2022,Unnamed: 6,2023,Unnamed: 8,2024,Unnamed: 10
1,계,51836.0,516.0,51770.0,515.0,51673.0,514.0,51713.0,515.0,51751.0,515.0
2,서울,9618.0,15891.0,9508.0,15709.0,9421.0,15567.0,9400.0,15533.0,9394.0,15521.0
3,부산,3356.0,4358.0,3334.0,4328.0,3303.0,4282.0,3284.0,4258.0,3265.0,4232.0
4,대구,2414.0,2733.0,2396.0,2711.0,2372.0,2679.0,2360.0,2666.0,2354.0,2659.0
5,인천,2951.0,2770.0,2950.0,2766.0,2975.0,2788.0,3009.0,2820.0,3049.0,2851.0
6,광주,1480.0,2952.0,1476.0,2945.0,1470.0,2933.0,1463.0,2921.0,1456.0,2905.0
7,대전,1492.0,2764.0,1482.0,2747.0,1472.0,2728.0,1474.0,2731.0,1473.0,2729.0
8,울산,1139.0,1072.0,1125.0,1059.0,1114.0,1048.0,1106.0,1041.0,1103.0,1038.0
9,세종,348.0,749.0,361.0,777.0,380.0,818.0,387.0,833.0,389.0,837.0
10,경기,13452.0,1319.0,13611.0,1335.0,13690.0,1342.0,13781.0,1351.0,13861.0,1359.0
11,강원,1519.0,90.0,1520.0,90.0,1527.0,91.0,1525.0,91.0,1518.0,90.0
12,충북,1631.0,220.0,1626.0,220.0,1623.0,219.0,1627.0,220.0,1630.0,220.0
13,충남,2177.0,264.0,2175.0,264.0,2186.0,265.0,2204.0,267.0,2224.0,270.0
14,전북,1806.0,224.0,1792.0,222.0,1777.0,220.0,1768.0,219.0,1759.0,218.0
15,전남,1793.0,145.0,1785.0,144.0,1775.0,144.0,1768.0,143.0,1757.0,142.0
16,경북,2652.0,139.0,2641.0,139.0,2626.0,138.0,2611.0,137.0,2597.0,136.0
17,경남,3340.0,317.0,3315.0,314.0,3287.0,312.0,3267.0,310.0,3249.0,308.0
18,제주,669.0,361.0,672.0,363.0,675.0,365.0,677.0,366.0,675.0,365.0
19,수도권,26021.0,2193.0,26069.0,2196.0,26086.0,2197.0,26190.0,2206.0,26304.0,2215.0

In [13]:
# 4. 연도별 총인구 및 평균 인구 변화 추이
years = [2020, 2021, 2022, 2023, 2024]
total_pop = {year: df[str(year)].sum() for year in years}
total_pop

{2020: np.float64(129694.0),
 2021: np.float64(129608.0),
 2022: np.float64(129432.0),
 2023: np.float64(129614.0),
 2024: np.float64(129808.0)}

In [14]:
# 5. 지역별 인구 증감률 (2020→2024)
df["증감률(2020~2024)"] = ((df["2024"] - df["2020"]) / df["2020"]) * 100
df

,지역,2020,Unnamed: 2,2021,Unnamed: 4,2022,Unnamed: 6,2023,Unnamed: 8,2024,Unnamed: 10,증감률(2020~2024)
1,계,51836.0,516.0,51770.0,515.0,51673.0,514.0,51713.0,515.0,51751.0,515.0,-0.163979
2,서울,9618.0,15891.0,9508.0,15709.0,9421.0,15567.0,9400.0,15533.0,9394.0,15521.0,-2.328967
3,부산,3356.0,4358.0,3334.0,4328.0,3303.0,4282.0,3284.0,4258.0,3265.0,4232.0,-2.711561
4,대구,2414.0,2733.0,2396.0,2711.0,2372.0,2679.0,2360.0,2666.0,2354.0,2659.0,-2.485501
5,인천,2951.0,2770.0,2950.0,2766.0,2975.0,2788.0,3009.0,2820.0,3049.0,2851.0,3.320908
6,광주,1480.0,2952.0,1476.0,2945.0,1470.0,2933.0,1463.0,2921.0,1456.0,2905.0,-1.621622
7,대전,1492.0,2764.0,1482.0,2747.0,1472.0,2728.0,1474.0,2731.0,1473.0,2729.0,-1.273458
8,울산,1139.0,1072.0,1125.0,1059.0,1114.0,1048.0,1106.0,1041.0,1103.0,1038.0,-3.160667
9,세종,348.0,749.0,361.0,777.0,380.0,818.0,387.0,833.0,389.0,837.0,11.781609
10,경기,13452.0,1319.0,13611.0,1335.0,13690.0,1342.0,13781.0,1351.0,13861.0,1359.0,3.040440
11,강원,1519.0,90.0,1520.0,90.0,1527.0,91.0,1525.0,91.0,1518.0,90.0,-0.065833
12,충북,1631.0,220.0,1626.0,220.0,1623.0,219.0,1627.0,220.0,1630.0,220.0,-0.061312
13,충남,2177.0,264.0,2175.0,264.0,2186.0,265.0,2204.0,267.0,2224.0,270.0,2.158934
14,전북,1806.0,224.0,1792.0,222.0,1777.0,220.0,1768.0,219.0,1759.0,218.0,-2.602436
15,전남,1793.0,145.0,1785.0,144.0,1775.0,144.0,1768.0,143.0,1757.0,142.0,-2.007808
16,경북,2652.0,139.0,2641.0,139.0,2626.0,138.0,2611.0,137.0,2597.0,136.0,-2.073906
17,경남,3340.0,317.0,3315.0,314.0,3287.0,312.0,3267.0,310.0,3249.0,308.0,-2.724551
18,제주,669.0,361.0,672.0,363.0,675.0,365.0,677.0,366.0,675.0,365.0,0.896861
19,수도권,26021.0,2193.0,26069.0,2196.0,26086.0,2197.0,26190.0,2206.0,26304.0,2215.0,1.087583

In [15]:
# 6. 인구 감소 지역 TOP 5
top5_decline = df.sort_values("증감률(2020~2024)").head(5)
top5_decline

,지역,2020,Unnamed: 2,2021,Unnamed: 4,2022,Unnamed: 6,2023,Unnamed: 8,2024,Unnamed: 10,증감률(2020~2024)
8,울산,1139.0,1072.0,1125.0,1059.0,1114.0,1048.0,1106.0,1041.0,1103.0,1038.0,-3.160667
17,경남,3340.0,317.0,3315.0,314.0,3287.0,312.0,3267.0,310.0,3249.0,308.0,-2.724551
3,부산,3356.0,4358.0,3334.0,4328.0,3303.0,4282.0,3284.0,4258.0,3265.0,4232.0,-2.711561
14,전북,1806.0,224.0,1792.0,222.0,1777.0,220.0,1768.0,219.0,1759.0,218.0,-2.602436
4,대구,2414.0,2733.0,2396.0,2711.0,2372.0,2679.0,2360.0,2666.0,2354.0,2659.0,-2.485501

In [16]:
print("연도별 총 인구:", total_pop)
print("\n인구 감소 지역 TOP 5:")
print(top5_decline[["지역", "증감률(2020~2024)"]])

연도별 총 인구: {2020: np.float64(129694.0), 2021: np.float64(129608.0), 2022: np.float64(129432.0), 2023: np.float64(129614.0), 2024: np.float64(129808.0)}

인구 감소 지역 TOP 5:
    지역  증감률(2020~2024)
8   울산       -3.160667
17  경남       -2.724551
3   부산       -2.711561
14  전북       -2.602436
4   대구       -2.485501